### ISSUE TITLE
Thats pretty cool! :) 

### ISSUE THREAD

**Issue by genaray** [proc-gen/roguelite-survivor#34]
Hey! Just saw your project and its actually pretty nice to see someone using Arch for something more advanced! 
Once complete, i could also showcase it on the Arch github page (if you want of course) ^^

I just took a quick look at your systems, If you want to reduce allocations, i would recommend to to use the static keyword `world.Query(in queryDesc, static (...) => {});` this way you make sure to prevent closure copies of objects or primitives. You could also look into the "InlineQuery" API, that one requires a bit more code but inlines your iterations for the best possible speed and performance (and it prevents closure copies).  Theres also [Arch.Extended](https://github.com/genaray/Arch.Extended) which provides a source generator to generate systems and methods on the fly for saving boilerplate code and native iteration speed :) 
https://github.com/genaray/Arch/wiki/Query-techniques

If you need help or tipps, feel free to ask! Im glad to help where i can! Keep up the work! :)

**Comment by proc-gen** [comment]
Thanks for checking out the project! 

I have taken a little bit of a look at the more advanced stuff and Arch.Extended, but right now I'm prioritizing getting things done and try to optimize later on if necessary. On my system it's currently playable with up to around 2000 enemies at once which is more than plenty for the time being. The only slowdown I've had other than that is in map rendering based on some performance testing I did with an earlier build.

Do you have any documentation on adding `static` into the query? I'm not sure if it would fix some intermittent issues I've had where with something like `(in Entity entity, ref Position pos)` that `entity.IsAlive()` comes back as true, but then it throws and exception when running `entity.Has<Enemy>()`. Other times I've had the `entity` and `pos` parameters come back for separate entities, although I solved that by changing how the targeting system worked.

The current branch I'm working on will replace all the boilerplate test maps with more RPG style maps with obstacles and such and be much more pleasant to play.

**Comment by genaray** [comment]
> The only slowdown I've had other than that is in map rendering based on some performance testing I did with an earlier build.

Yeah i feel that, rendering is always a bit tricky. Had the same problem in my monogame sample. There actually solutions to it ( instanced rendering e.g. ), however those are a bit tricky. 

> Do you have any documentation on adding `static` into the query?

Not yet, but I'm gonna add that :) Its more like a .Net7 feature for lambdas in general.
`world.Query(in queryDesc, static (in Entity en) => { /** Here we are now forced to only use global variables or the entity to prevent closure copies **/  });`

> `(in Entity entity, ref Position pos)` that `entity.IsAlive()` comes back as true, but then it throws and exception when running `entity.Has<Enemy>()`

Thats interesting... This actually sounds like a bug. Do you know which exception was thrown? And in which Arch version this happened ? (the latest 1.2.0 actually fixed a bunch of bugs, so it might be gone) ^^

**Comment by proc-gen** [comment]
> Yeah i feel that, rendering is always a bit tricky. Had the same problem in my monogame sample. There actually solutions to it ( instanced rendering e.g. ), however those are a bit tricky.

It's not even that it's slow, just that it was taking up 60% of the processing time compared to everything else. 

> Not yet, but I'm gonna add that :) Its more like a .Net7 feature for lambdas in general. `world.Query(in queryDesc, static (in Entity en) => { /** Here we are now forced to only use global variables or the entity to prevent closure copies **/ });`

Nice! I'll have to take a look at this some more. I haven't looked into any of the new features of .Net7 yet.

> Thats interesting... This actually sounds like a bug. Do you know which exception was thrown? And in which Arch version this happened ? (the latest 1.2.0 actually fixed a bunch of bugs, so it might be gone) ^^
> 
> All Queries should only process valid/living entities. So actually all those `entity.Alive()` checks are unnecessary (in theory, or you just discovered a arch bug which is critical).

This is as close as I can get to the errors from when I was debugging. They're leftover from my command window when I was trying to figure things out. I'll upgrade from 1.1.9 ->1.2.0 and if I see the error again I'll get a more detailed set of information for you to look at.

`>? other.GetAllComponents()
'other.GetAllComponents()' threw an exception of type 'System.IndexOutOfRangeException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233080
    HelpLink: null
    InnerException: null
    Message: "Index was outside the bounds of the array."
    Source: "System.Private.CoreLib"
    StackTrace: "   at System.ThrowHelper.ThrowIndexOutOfRangeException()\r\n   at System.Array.GetFlattenedIndex(Int32 rawIndex)\r\n   at Arch.Core.Extensions.EntityExtensions.GetAllComponents(Entity& entity)"
    TargetSite: {Void ThrowIndexOutOfRangeException()}`

`>? entity.GetAllComponents()
'entity.GetAllComponents()' threw an exception of type 'System.Collections.Generic.KeyNotFoundException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146232969
    HelpLink: null
    InnerException: null
    Message: "Key not found: 107"
    Source: "Collections.Pooled"
    StackTrace: "   at Collections.Pooled.ThrowHelper.ThrowKeyNotFoundException[T](T key)\r\n   at Arch.Core.Extensions.EntityExtensions.GetAllComponents(Entity& entity)"
    TargetSite: {Void ThrowKeyNotFoundException[T](T)}`

**Comment by genaray** [comment]
Alright thanks ^^ Would be great to report the error if it should happen again.

I also forked your project and optimizing some of the ecs code. E.g. the `entity.IsAlive()` checks are actually necessary since queries only process valid living entities. And `entity.SetRange` should only be used if the types are unknown during compile time, `.Set` is the faster and alloc free variant :) 

I actually do this to reproduce the exception to see when exactly it happens. But if you want i can also create a PR later to push the "optimized" code, this could probably save you some time ^^

**Comment by proc-gen** [comment]
>I actually do this to reproduce the exception to see when exactly it happens. But if you want i can also create a PR later to push the "optimized" code, this could probably save you some time ^^

Feel free to work on a PR for the optimized ECS stuff. This project is meant to stay free to use and at most might get made into a free game on something after I've gotten more done. I'll just need to add something more to the credits screen for those who help out with the programming :)

If you remove the `entity.IsAlive()` check from the AnimationUpdateSystem, it looks like that's the quickest spot to get the crash to occur. This is after removing all the checks and upgrading to 1.2.0.

```
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=Key not found: 4
  Source=Collections.Pooled
  StackTrace:
   at Collections.Pooled.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at Collections.Pooled.PooledDictionary`2.get_Item(TKey key)
   at Arch.Core.Extensions.EntityExtensions.Has[T](Entity& entity)
   at RogueliteSurvivor.Systems.AnimationUpdateSystem.<>c__DisplayClass1_0.<Update>b__0(Entity& entity, Animation& anim) in ~\roguelite-survivor\RogueliteSurvivor\RogueliteSurvivor\Systems\AnimationUpdateSystem.cs:line 35
   at Arch.Core.World.Query[T0](QueryDescription& description, ForEachWithEntity`1 forEach)
   at RogueliteSurvivor.Systems.AnimationUpdateSystem.Update(GameTime gameTime, Single totalElapsedTime) in ~\roguelite-survivor\RogueliteSurvivor\RogueliteSurvivor\Systems\AnimationUpdateSystem.cs:line 19
   at RogueliteSurvivor.Scenes.GameScene.Update(GameTime gameTime, Object[] values) in ~\roguelite-survivor\RogueliteSurvivor\RogueliteSurvivor\Scenes\GameScene.cs:line 331
   at RogueliteSurvivor.Game1.Update(GameTime gameTime) in ~\roguelite-survivor\RogueliteSurvivor\RogueliteSurvivor\Game1.cs:line 115
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Program.<Main>$(String[] args) in ~\roguelite-survivor\RogueliteSurvivor\RogueliteSurvivor\Program.cs:line 4
```

**Comment by genaray** [comment]
Great than im gonna push a small changes in a few minutes :)

> If you remove the `entity.IsAlive()` check from the AnimationUpdateSystem

Now its getting interesting... i have ALL `entity.IsAlive()` checks removed (also in other systems) and mine does not crash. Neither the 1.1.9 nor the 1.2.0 version. Atleast i just ran around for 10 minutes on the demo map with a lightning mage and had no single crash. This is interesting... 

https://imgur.com/a/ldaCcwA

**Comment by proc-gen** [comment]
Maybe try pulling my current branch? https://github.com/proc-gen/roguelite-survivor/tree/real-maps

There's not nearly as many enemies on either map there so far, but it happened on The Church within around 30 seconds or so.

**Comment by genaray** [comment]
> Maybe try pulling my current branch? https://github.com/proc-gen/roguelite-survivor/tree/real-maps
> 
> There's not nearly as many enemies on either map there so far, but it happened on The Church within around 30 seconds or so.

Ah i see... i only tested the master. One sec, I'm gonna investigate :)

**Comment by genaray** [comment]
Yeah i see... it crashes after about 30 sec. Looks like it does not crash in debug however.
Very weird, also... why did it worked on the master? 

Im gonna investigate that issue ^^

**Comment by proc-gen** [comment]
Did you make all the same changes from your PR? I think I caught everything from it and have it merged into the branch. The only one that still seems to need the `IsAlive()` check is the `AnimationUpdateSystem` when it fails checking `entity.Has<Burn>()` because of the Key Not Found exception.

**Comment by genaray** [comment]
Yep i did the same changes :/ Yeah its totally a bug. Btw how do you even receive the log? The console never prints anything and i couldn't find any log files nor log calls. And once the debugger is attached, the bug is gone. So its actually kinda hard to debug.

**Comment by proc-gen** [comment]
I'm running this in VS 2022, so I'm not sure what you'd need to do if you're using a different IDE.

I was able to fix it in `AnimationUpdateSystem` with a refactor that no longer needs the entity itself.

```
world.Query(in query, (ref Animation anim) =>
            {
                anim.Count += (float)gameTime.ElapsedGameTime.Ticks / TimeSpan.TicksPerSecond;
                if (anim.Count > anim.Max)
                {
                    anim.Count = 0;
                    if (anim.Repeatable)
                    {
                        anim.CurrentFrame = anim.CurrentFrame == anim.LastFrame ? anim.FirstFrame : anim.CurrentFrame + 1;
                    }
                    else
                    {
                        anim.CurrentFrame = anim.CurrentFrame == anim.LastFrame ? anim.LastFrame : anim.CurrentFrame + 1;
                    }

                    anim.Overlay = Color.White;
                }
            });

            world.Query(in burnQuery, (ref Animation anim) =>
            {
                anim.Overlay = Color.Orange;
            });

            world.Query(in slowQuery, (ref Animation anim) =>
            {
                anim.Overlay = Color.Blue;
            });

            world.Query(in shockQuery, (ref Animation anim) =>
            {
                anim.Overlay = Color.Yellow;
            });
```

However, that just results in it crashing elsewhere for the same issue. Is it possible it's stemming from the status components(Burn, Slow, and Shock) not being part of the main archetypes I'm using. I could see moving back and forth by adding/removing those components making it difficult to keep track of the entity properly.

**Comment by genaray** [comment]
Im using Rider and unfortunately i dont get any console output, however the debugging now works at least. 

Your refactoring is actually quite smart, this way only the certain archetypes are being iterated on and there no checks required ^^ 

Im already working actively on this issue since this is a critical one. I just pulled the arch sources into this project to quickly iterate a solution. And yes you are right, it looks like the Adding/Removing operation is messing something up. I just haven't figured out why, since all the atomic unit tests are fine. This also explains why you had problems with component values that do not fit the entity, i just saw that the same entity exists in two different archetypes. That would easily explain that problem.

Working on it, letting you know if i found the source of the bug :)

**Comment by proc-gen** [comment]
Good luck figuring it out! I refactored some things in `CollisionSystem` as well, so the only place that seems to need the `IsAlive()` check at the moment is the `GameContactFilter`.

**Comment by genaray** [comment]
Nice! :) I actually think i found the issue and could fix it : https://github.com/genaray/roguelite-survivor/commit/a325953bd93948eb3e50084c617c054cb8cca753

Looks like there was a logical issue in that forgot to cache the entity id and reassign the archetype during moves which could easily lead to undefined behaviour... like entities in wrong archetypes (since it wasn't reassigned after moving) or even sudden entity disappearing which caused the crash.

Would be great if you could test out the linked fork. I ran it like 6 times in a row with up to 4-5 minutes playtime and there was no crash. So i think its solved now?

**Comment by proc-gen** [comment]
I pulled the branch locally, but I'm not having any luck running it for some reason.

If you want to guarantee that the spell effects get added, you can edit the `spells.json` file to increase the chance. 

Maybe it would be worth posting a beta version to nuget if you aren't sure it fixes everything? Appreciate all the time you're putting in getting this working!

**Comment by genaray** [comment]
Ah i see, gonna do that :) 

No luck? What do you mean? Make sure the source generator runs (clean cache, build project again, probably restart vs). Then it should work :) 

Aye i could do that, looking into it rn. Probably a bit cleaner to test ^^

**Comment by proc-gen** [comment]
I got it running! VS made it necessary to unload and reload both Arch projects after I pulled down your code.

At this point I don't see any reason why the fix won't work. Hard to say though since there's no exact way to cause it to crash other than what I mentioned before.

**Comment by genaray** [comment]
Great! :) So it did not crash and you think it works? 
Im gonna upload the beta nuget in a few minutes, that should show longterm if it works or not ^^

**Comment by proc-gen** [comment]
Thanks! I've got it added to my next working branch and it all looks good.

🤞 that's the only major bug and you can focus on making Arch more awesome now
