### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by genaray** [proc-gen/roguelite-survivor#72]
Just wanted to try it out again to see whats new :) 
However i ran into a crash and following errors which were logged here:

[error-20230416171108.txt](https://github.com/proc-gen/roguelite-survivor/files/11242596/error-20230416171108.txt)
[error-20230416171122.txt](https://github.com/proc-gen/roguelite-survivor/files/11242597/error-20230416171122.txt)
[error-20230416171128.txt](https://github.com/proc-gen/roguelite-survivor/files/11242598/error-20230416171128.txt)

**Comment by proc-gen** [comment]
Interesting. Can you take a look at your `~/Saves/savegame.json` file? It seems like when it created the new section that it didn't create the individual fields within it.

**Comment by proc-gen** [comment]
Here's an example of what should be at the end of the file:

```
"NumBooks": 200,
  "PlayerUpgrades": {
    "Health": 8,
    "Damage": 8,
    "SpellEffectChance": 0,
    "Pierce": 1,
    "AttackSpeed": 0,
    "AreaOfEffect": 0,
    "MoveSpeed": 16
  }
```

**Comment by genaray** [comment]
> Interesting. Can you take a look at your `~/Saves/savegame.json` file? It seems like when it created the new section that it didn't create the individual fields within it.

Here you go ^^ : 
```
{
  "LevelProgressions": [
    {
      "Name": "The Beginning",
      "BestTime": 0.0
    },
    {
      "Name": "The Church",
      "BestTime": 0.0
    },
    {
      "Name": "The Underground",
      "BestTime": 0.0
    }
  ],
  "EnemyKillStats": null,
  "NumBooks": 0,
  "PlayerUpgrades": null
}
```

**Comment by proc-gen** [comment]
Oof... looks like with all the incremental updating I've done to that file I haven't tested a clean version lately.

**Comment by proc-gen** [comment]
If you delete the existing `savegame.json` and then start the game, everything should work now. I was only instantiating the map progress for a brand new file, so the incremental updates always worked and created the new sections as needed.

**Comment by genaray** [comment]
Ah it works now! :D Nice!
It also looks really good, i can clearly see that a lot of work went in there ^^ 
Do you mind if i feature it on the Arch github? I think its time for a "projects" category :> 

Do you have any thumbnail or in game screenshot? ^^

**Comment by proc-gen** [comment]
I can throw some stuff together with that. Let me get another set of changes in that includes links for all the assets that aren't mine. I know they're listed out in the credits file and in-game, but I'd like to include links as well.

**Comment by genaray** [comment]
> I can throw some stuff together with that. Let me get another set of changes in that includes links for all the assets that aren't mine. I know they're listed out in the credits file and in-game, but I'd like to include links as well.

Yeah that would be great! :) Just saw you updated the links. Should i take a screenshot of an ingame scene? Or do you want to do that? ^^

**Comment by proc-gen** [comment]
If you want to get it up right away, sure, otherwise I can do that later today.

**Comment by genaray** [comment]
> If you want to get it up right away, sure, otherwise I can do that later today.

That would be great ^^

**Comment by proc-gen** [comment]
![image](https://user-images.githubusercontent.com/65076703/232624411-6a9e8a29-3118-41a6-a8f3-dd8d9c8f0edf.png)

**Comment by proc-gen** [comment]
Looks like the HUD needs some slight updating because of the text size, but I think that's a good enough screenshot for what you need.

**Comment by genaray** [comment]
Its now listed here https://github.com/genaray/Arch/wiki/Projects-using-Arch and on the main page :) 
If you have any improvements, lemme know!
